name: Build and Push Docker Image with Packer
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Initialize Packer
        run: packer init .

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest

      - name: Build with Packer
        run: |
          packer build \
            -var "image_tag=sha-${{ github.sha }}" \
            -var "registry_username=${{ github.actor }}"
            -var "registry_password=${{ secrets.GITHUB_TOKEN }}"
            .

      - name: Deploy to Nomad
        uses: SpyicyDev/nomad-job-runner-action@v1.0.0
        env:
          NOMAD_VAR_image_tag: sha-${{ github.sha }}
        with:
          job_spec_file: jobspec.nomad.hcl
          cloudflare_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          cloudflare_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}
          nomad_proxy_pass: https://nomad.mackhaymond.co
