---
name: test connect
on:
    push:
      branches:
        - main
    workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test requests
        run: |
          curl --location -H "CF-Access-Client-Id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}" -H "CF-Access-Client-Secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}" https://nomad.mackhaymond.co

      - name: Setup `nomad`
        uses: hashicorp/setup-nomad@main
        id: setup
        with:
          version: latest

      - name: Run Nomad Job
        run: |
          NOMAD_ADDR=https://nomad.mackhaymond.co nomad job run nomad_jobspec.hcl
