
---
name: test connect
on:
    push:
      branches:
        - main
    workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Cloudflare Warp
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: spyicydev
          auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}
          configure_docker_dns: true
      - name: test it
        run: |
          curl https://www.cloudflare.com/cdn-cgi/trace/
          curl --location -v https://nomad.mackhaymond.co
      - name: Setup `nomad`
        uses: hashicorp/setup-nomad@main
        id: setup
        with:
          version: latest
      - name: Run Nomad Job
        run: |
          NOMAD_ADDR=https://nomad.mackhaymond.co nomad job run nomad_jobspec.hcl
