name: test connect
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test requests
        run: |
          curl --location \
            -H "CF-Access-Client-Id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}" \
            https://nomad.mackhaymond.co

      - name: Setup Nginx Reverse Proxy
        run: |
          # Write the Nginx configuration to a file
          cat << 'EOF' > nginx.conf
          events {}
          http {
            server {
              listen 80;
              location / {
                proxy_pass https://nomad.mackhaymond.co;
                proxy_set_header CF-Access-Client-Id $CF_ACCESS_CLIENT_ID;
                proxy_set_header CF-Access-Client-Secret $CF_ACCESS_CLIENT_SECRET;
              }
            }
          }
          EOF

          # Start an Nginx container with the above config
          docker run -d --rm --name nginx-proxy -p 8080:80 \
            -e CF_ACCESS_CLIENT_ID="${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}" \
            -e CF_ACCESS_CLIENT_SECRET="${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}" \
            -v "$(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro" \
            nginx:stable

      - name: Setup `nomad`
        uses: hashicorp/setup-nomad@main
        with:
          version: latest

      - name: Run Nomad Job
        env:
          # Point Nomad to the local proxy instead of the actual URL.
          NOMAD_ADDR: http://localhost:8080
        run: |
          nomad job run nomad_jobspec.hcl
